[package]
name = "yayagram"
version = "0.4.0"
authors = ["r00ster91 <r00ster91@protonmail.com>"]
edition = "2018"
description = "Play nonograms/picross in your terminal"
readme = "README.md"
repository = "https://github.com/r00ster91/yayagram/"
license = "MIT"
keywords = ["cli", "game", "terminal", "graphics", "puzzle"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal = { package = "tanmatsu", version = "0.2.5" }
rand = { version = "0.8.3", features = ["small_rng"] }
itertools = "0.10.0"
line_drawing = "0.8.0"

# Compact build mode:
#
# [profile.release]
# opt-level = "z"
# lto = true
# codegen-units = 1
